USE `cancel`;

CREATE TABLE `user_credentials` (
	`ID` VARCHAR(16) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_ID` VARCHAR(16) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_NAME` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_PASSWORD` VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_ROLE` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`ENABLED` TINYINT(4) NULL DEFAULT '1',
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `USER_NAME` (`USER_NAME`) USING BTREE,
	INDEX `USER_ID` (`USER_ID`) USING BTREE
)
COLLATE='utf8_czech_ci'
ENGINE=MyISAM
;

/*Data for the table `user_credentials` */
INSERT  INTO `user_credentials`(`ID`, `USER_ID`, `USER_NAME`,`USER_PASSWORD`,`USER_ROLE`, `ENABLED`) VALUES (
  'US01_A0000000000', 
  'US00_A0000000000', 
  'roy', '$2a$12$PN0MjtyNGWW.AjWdIuYKxe4.4Grjs4K7oanuAnt/WSDSvFlUc3eQi',
  'ROLE_ADMIN',
  1
);
