CREATE TABLE `user_account` (
	`ID` VARCHAR(20) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`GIVEN_NAME` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`SURNAME` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`MAIL` VARCHAR(50) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`AUTORIZED` TINYINT(1) NOT NULL DEFAULT '0',
	`CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `user_account_GIVEN_NAME_idx` (`GIVEN_NAME`) USING BTREE,
	INDEX `user_account_SURNAME_idx` (`SURNAME`) USING BTREE,
	INDEX `user_account_MAIL_idx` (`MAIL`) USING BTREE
)
COLLATE='utf8_czech_ci'
ENGINE=MyISAM
;
CREATE TABLE `user_credentials` (
	`ID` VARCHAR(16) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_ID` VARCHAR(16) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_NAME` VARCHAR(64) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_PASSWORD` VARCHAR(64) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`USER_ROLE` VARCHAR(32) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`ENABLED` TINYINT(4) NULL DEFAULT '1',
	PRIMARY KEY (`ID`) USING BTREE,
	UNIQUE INDEX `USER_NAME` (`USER_NAME`) USING BTREE,
	INDEX `USER_ID` (`USER_ID`) USING BTREE
)
COLLATE='utf8_czech_ci'
ENGINE=MyISAM
;
